import type { Article, Author, Category, Publication, Service } from "@/types/content";

/**
 * PLACEHOLDER CONTENT.
 *
 * Every record below is invented scaffolding that exists so the public site can
 * be laid out and reviewed before the database lands in Phase 4. None of it is
 * supplied company information. Titles, authors and ISBNs are fictional and are
 * expected to be replaced wholesale by seeded data.
 */

export const categories: Category[] = [
  {
    id: "c1",
    name: "Fiction",
    slug: "fiction",
    description: "Novels and short story collections.",
  },
  {
    id: "c2",
    name: "Non-fiction",
    slug: "non-fiction",
    description: "Memoir, history, essays and reportage.",
  },
  {
    id: "c3",
    name: "Academic",
    slug: "academic",
    description: "Scholarly monographs and textbooks.",
  },
  {
    id: "c4",
    name: "Children's",
    slug: "childrens",
    description: "Picture books and early readers.",
  },
];

export const authors: Author[] = [
  {
    id: "a1",
    name: "Amara Osei",
    slug: "amara-osei",
    role: "Novelist",
    bio: "Placeholder biography. Amara writes literary fiction concerned with migration, memory and the households that hold both. Her work has appeared in several anthologies.",
    featured: true,
    socials: [{ label: "Website", href: "https://example.com" }],
  },
  {
    id: "a2",
    name: "Daniel Mensah",
    slug: "daniel-mensah",
    role: "Historian",
    bio: "Placeholder biography. Daniel researches twentieth-century trade routes and writes narrative history for general readers.",
    featured: true,
  },
  {
    id: "a3",
    name: "Priya Raman",
    slug: "priya-raman",
    role: "Essayist",
    bio: "Placeholder biography. Priya writes essays on technology, labour and the built environment.",
    featured: false,
  },
  {
    id: "a4",
    name: "Tom Whitfield",
    slug: "tom-whitfield",
    role: "Children's author",
    bio: "Placeholder biography. Tom writes and illustrates picture books for early readers.",
    featured: true,
  },
  {
    id: "a5",
    name: "Lena Fischer",
    slug: "lena-fischer",
    role: "Academic",
    bio: "Placeholder biography. Lena lectures in comparative literature and edits a scholarly series.",
    featured: false,
  },
];

const day = (iso: string) => new Date(`${iso}T00:00:00.000Z`);

export const publications: Publication[] = [
  {
    id: "p1",
    title: "The Cartographer's Daughter",
    slug: "the-cartographers-daughter",
    authorId: "a1",
    categoryId: "c1",
    isbn: "978-0-0000000-0-1",
    description:
      "Placeholder description. A novel following three generations of a family of mapmakers, and the borders that outlive them. Told across two continents and sixty years, it asks what is lost when a place is drawn rather than remembered.",
    excerpt: "Three generations of mapmakers, and the borders that outlive them.",
    publicationDate: day("2025-03-18"),
    format: "hardcover",
    pages: 384,
    featured: true,
    status: "published",
  },
  {
    id: "p2",
    title: "Salt Roads",
    slug: "salt-roads",
    authorId: "a2",
    categoryId: "c2",
    isbn: "978-0-0000000-0-2",
    description:
      "Placeholder description. A narrative history of the inland salt trade and the towns it built, drawing on ledgers, letters and oral accounts collected over a decade.",
    excerpt: "A narrative history of the inland salt trade and the towns it built.",
    publicationDate: day("2024-11-05"),
    format: "paperback",
    pages: 312,
    featured: true,
    status: "published",
  },
  {
    id: "p3",
    title: "Small Machines",
    slug: "small-machines",
    authorId: "a3",
    categoryId: "c2",
    isbn: "978-0-0000000-0-3",
    description:
      "Placeholder description. Essays on the tools we build to avoid difficult decisions, and what they reveal about the people who commission them.",
    excerpt: "Essays on the tools we build to avoid difficult decisions.",
    publicationDate: day("2025-06-24"),
    format: "ebook",
    pages: 208,
    featured: false,
    status: "published",
  },
  {
    id: "p4",
    title: "Where the Kites Go",
    slug: "where-the-kites-go",
    authorId: "a4",
    categoryId: "c4",
    isbn: "978-0-0000000-0-4",
    description:
      "Placeholder description. A picture book about a child who follows a lost kite across a city and finds the people who live beneath it.",
    excerpt: "A picture book about a lost kite and the city beneath it.",
    publicationDate: day("2025-01-30"),
    format: "hardcover",
    pages: 40,
    featured: true,
    status: "published",
  },
  {
    id: "p5",
    title: "Reading the Interval",
    slug: "reading-the-interval",
    authorId: "a5",
    categoryId: "c3",
    isbn: "978-0-0000000-0-5",
    description:
      "Placeholder description. A comparative study of pause, silence and the unwritten in twentieth-century prose, intended for postgraduate readers.",
    excerpt: "A comparative study of pause and silence in twentieth-century prose.",
    publicationDate: day("2024-09-12"),
    format: "paperback",
    pages: 276,
    featured: false,
    status: "published",
  },
  {
    id: "p6",
    title: "The Long Commission",
    slug: "the-long-commission",
    authorId: "a1",
    categoryId: "c1",
    isbn: "978-0-0000000-0-6",
    description:
      "Placeholder description. A short novel about an architect asked to design a building for a town that is being moved, stone by stone, to higher ground.",
    excerpt: "An architect designs for a town that is being moved to higher ground.",
    publicationDate: day("2023-08-01"),
    format: "paperback",
    pages: 190,
    featured: false,
    status: "published",
  },
  {
    id: "p7",
    title: "Night Shift at the Observatory",
    slug: "night-shift-at-the-observatory",
    authorId: "a3",
    categoryId: "c1",
    isbn: "978-0-0000000-0-7",
    description:
      "Placeholder description. Linked short stories set among the staff of a mountain observatory across a single winter.",
    excerpt: "Linked stories set among the staff of a mountain observatory.",
    publicationDate: day("2025-09-02"),
    format: "audiobook",
    pages: 240,
    featured: false,
    status: "published",
  },
  {
    id: "p8",
    title: "A Grammar of Harbours",
    slug: "a-grammar-of-harbours",
    authorId: "a5",
    categoryId: "c3",
    isbn: "978-0-0000000-0-8",
    description:
      "Placeholder description. An academic treatment of port cities as linguistic contact zones, with case studies drawn from four coastlines.",
    excerpt: "Port cities read as linguistic contact zones.",
    publicationDate: day("2025-05-14"),
    format: "hardcover",
    pages: 420,
    featured: false,
    status: "published",
  },
  {
    id: "p9",
    title: "Unfinished Drafts",
    slug: "unfinished-drafts",
    authorId: "a2",
    categoryId: "c2",
    isbn: "978-0-0000000-0-9",
    description: "Placeholder description. A working manuscript not yet released.",
    excerpt: "A working manuscript not yet released.",
    publicationDate: day("2026-04-01"),
    format: "paperback",
    pages: 300,
    featured: false,
    status: "draft",
  },
];

export const articles: Article[] = [
  {
    id: "n1",
    title: "Announcing our spring list",
    slug: "announcing-our-spring-list",
    excerpt: "Eight new titles across fiction, history and children's books.",
    body: "Placeholder article body.\n\nThis paragraph stands in for editorial copy so the article layout, measure and typography can be reviewed. It will be replaced by real content entered through the admin in Phase 6.\n\nA second paragraph demonstrates spacing between blocks, and gives the prose styles something to work with at a realistic length.",
    authorName: "Editorial team",
    categoryId: "c2",
    tags: ["announcements", "catalogue"],
    publishedAt: day("2025-08-19"),
    status: "published",
    featured: true,
  },
  {
    id: "n2",
    title: "How we read submissions",
    slug: "how-we-read-submissions",
    excerpt: "What happens to a manuscript between arriving and being answered.",
    body: "Placeholder article body.\n\nAn explanation of the reading process would sit here, describing the stages a submission passes through and roughly how long each takes.\n\nReplace with real editorial guidance before launch.",
    authorName: "Editorial team",
    categoryId: "c2",
    tags: ["submissions", "process"],
    publishedAt: day("2025-07-02"),
    status: "published",
    featured: true,
  },
  {
    id: "n3",
    title: "In conversation with Amara Osei",
    slug: "in-conversation-with-amara-osei",
    excerpt: "The novelist on maps, inherited silence, and writing across generations.",
    body: "Placeholder article body.\n\nAn interview transcript would sit here, formatted as alternating question and answer paragraphs.\n\nReplace with the real conversation before launch.",
    authorName: "Editorial team",
    categoryId: "c1",
    tags: ["interviews", "authors"],
    publishedAt: day("2025-05-28"),
    status: "published",
    featured: false,
  },
  {
    id: "n4",
    title: "Notes on our typesetting standards",
    slug: "notes-on-our-typesetting-standards",
    excerpt: "The house rules behind every interior we produce.",
    body: "Placeholder article body.\n\nA description of typesetting conventions would sit here.\n\nReplace before launch.",
    authorName: "Production team",
    categoryId: "c3",
    tags: ["production"],
    publishedAt: day("2025-02-11"),
    status: "published",
    featured: false,
  },
  {
    id: "n5",
    title: "Draft: autumn catalogue preview",
    slug: "draft-autumn-catalogue-preview",
    excerpt: "Not yet published.",
    body: "Placeholder article body for an unpublished draft.",
    authorName: "Editorial team",
    categoryId: "c2",
    tags: ["catalogue"],
    publishedAt: day("2026-02-01"),
    status: "draft",
    featured: false,
  },
];

export const services: Service[] = [
  {
    id: "s1",
    title: "Editorial assessment",
    slug: "editorial-assessment",
    summary: "A structured read of your manuscript with a written report and next steps.",
    body: "Placeholder service description. A full explanation of what the assessment covers, who carries it out and what the author receives would sit here.",
    icon: "FileSearch",
    order: 1,
    status: "published",
  },
  {
    id: "s2",
    title: "Copy-editing and proofreading",
    slug: "copy-editing-and-proofreading",
    summary: "Line-level editing for consistency, accuracy and house style.",
    body: "Placeholder service description covering the editing stages, turnaround and how changes are returned to the author.",
    icon: "PenLine",
    order: 2,
    status: "published",
  },
  {
    id: "s3",
    title: "Design and typesetting",
    slug: "design-and-typesetting",
    summary: "Cover design and interior layout prepared to print specification.",
    body: "Placeholder service description covering cover concepts, interior templates and print-ready file delivery.",
    icon: "LayoutTemplate",
    order: 3,
    status: "published",
  },
  {
    id: "s4",
    title: "Printing and production",
    slug: "printing-and-production",
    summary: "Short and long print runs managed end to end.",
    body: "Placeholder service description covering paper stock, binding options, proofing and print scheduling.",
    icon: "Printer",
    order: 4,
    status: "published",
  },
  {
    id: "s5",
    title: "Distribution",
    slug: "distribution",
    summary: "Getting finished titles into online retailers and bookshops.",
    body: "Placeholder service description covering retail channels, metadata feeds and stock handling.",
    icon: "Truck",
    order: 5,
    status: "published",
  },
  {
    id: "s6",
    title: "Publicity and marketing",
    slug: "publicity-and-marketing",
    summary: "Campaigns built around a title's audience and publication date.",
    body: "Placeholder service description covering review outreach, events and paid promotion.",
    icon: "Megaphone",
    order: 6,
    status: "published",
  },
];
